#!/bin/sh
#
# Start telnet server
#

LIGHTCAM_ARGS="/etc/lightcam.yml"


start() {
      printf "Starting lightcam: "
      [ -f /usr/sbin/lightcam ] || echo -en "DISABLED, "
      start-stop-daemon -S -q -m -b -p /var/run/lightcam.pid \
			-x /usr/sbin/lightcam -- $LIGHTCAM_ARGS
      [ $? = 0 ] && echo "OK" || echo "FAIL"
}

stop() {
	printf "Stopping lightcam: "
	[ -f /usr/sbin/lightcam ] || echo -en "DISABLED, "
	start-stop-daemon -K -q -p /var/run/lightcam.pid \
			  -x /usr/sbin/lightcam
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}

case "$1" in
    start)
	start
	;;
    stop)
	stop
	;;
    restart|reload)
	stop
	start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
